### ISSUE TITLE
Add a /health endpoint to microservice

### ISSUE THREAD

**Issue by xt2256** [CSCI-GA-2820-FA24-001/recommendations#67]
Add a /health endpoint to microservice that returns {"status":"OK"} and 200_OK return code so that Kubernetes knows that your microservice is healthy.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a new /health endpoint to the routes.py file that returns {"status":"OK"} with a 200_OK status code. This endpoint will help Kubernetes determine if the microservice is healthy.

You can review changes in this commit: https://github.com/lattaai13/CSCI-GA-2820-FA24-001-recommendations-67/commit/bfef903d08e596114cbd5533e95cc124c9138d16.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
